config/routes.rb
Weidulog::Application.routes.draw do
  resources :logs, :only => [:index, :show, :new, :create]
  resources :mods
  root :to => "logs#new"
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :logs
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :game
  has_one :content, :class_name => 'LogContent'
  has_and_belongs_to_many :mods
  has_and_belongs_to_many :mod_components, :class_name => 'Mod::Component'
  has_and_belongs_to_many :mod_versions, :class_name => 'Mod::Version'

  accepts_nested_attributes_for :content

  after_save :parse_mods, :calculate_counts

  validates_presence_of :game, :author

  private
    def parse_mods
      mods.clear

      content.body.each_line do |line|
        matches = line.match(content.regex)

        if matches
          mod_name, component_number, component_label, mod_version = matches[1..4]

          mod       = Mod.find_or_create_by_tp2_name(mod_name)
          component = mod.components.find_or_create_by_number_and_label(component_number, component_label)
          version   = mod.versions.find_or_create_by_number(mod_version)

          mods           << mod       unless mod_ids.include?(mod.id)
          mod_components << component unless mod_component_ids.include?(component.id)
          mod_versions   << version   unless mod_version_ids.include?(version.id)
        end
      end
    end

    def calculate_counts
      Log.update_all({:mod_count => mods.count, :mod_component_count => mod_components.count}, {:id => id})
    end
end

app/models/log_content.rb
class LogContent < ActiveRecord::Base
  belongs_to :log

  before_validation :read_log
  validates_presence_of :file
  validate :valid_log

  attr_accessor :file

  def regex
    /^~(?:(?:.+?)\/)?(?:SETUP-)?(.+?)\.TP2~\s#\d+\s#(\d+)\s\/\/\s(.+?)(?::\sv?([\d\.]+)\s?)?$/
  end

  private
    def read_log
      self.body = file.try(:read)
    end

    def valid_log
      errors.add(:file, 'is not a valid WeiDU log') unless body.try(:match, regex)
    end
end

app/models/mod.rb
class Mod < ActiveRecord::Base
  has_many :components
  has_many :versions
  has_and_belongs_to_many :logs

  before_create :guess_name

  private
    def guess_name
      self.name = tp2_name.titleize.gsub(/(bgt?|npc)/i){$1.upcase} if name.blank?
    end
end

app/models/mod/component.rb
class Mod::Component < ActiveRecord::Base
  belongs_to :mod
  has_and_belongs_to_many :logs
end

app/models/mod/version.rb
class Mod::Version < ActiveRecord::Base
  belongs_to :mod
  has_and_belongs_to_many :logs
end

app/models/mod_component.rb
class ModComponent < ActiveRecord::Base
  belongs_to :mod
  has_and_belongs_to_many :logs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    params[:order_by]        ||= 'created_at'
    params[:order_direction] ||= 'desc'

    if filters = params[:filters].try(:dup)
      date = filters.delete(:created_at_eq)

      unless date.blank?
        filters[:created_at_greater_than] = Time.parse(date).to_s(:db)
        filters[:created_at_less_than]    = Time.parse(date).tomorrow.to_s(:db)
      end

      @logs = Log.order(params[:order_by] + ' ' + params[:order_direction]).search(filters).all
    else
      @logs = Log.order(params[:order_by] + ' ' + params[:order_direction])
    end

    respond_to do |format|
      format.html
      format.xml  { render :xml => @logs }
    end
  end

  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html
      format.xml  { render :xml => @log }
    end
  end

  def new
    @log = Log.new
    @log.content = LogContent.new

    respond_to do |format|
      format.html
      format.xml  { render :xml => @log }
    end
  end

  def create
    @log = Log.new(params[:log])
    @log.content ||= LogContent.new

    respond_to do |format|
      if verify_recaptcha(:model => @log) && @log.save
        format.html { redirect_to(@log, :notice => 'Log was successfully created.') }
        format.xml  { render :xml => @log, :status => :created, :location => @log }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @log.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/mods_controller.rb
class ModsController < ApplicationController
  def index
    params[:order_by]        ||= 'name'
    params[:order_direction] ||= 'asc'

    @mods = Mod.order(params[:order_by] + ' ' + params[:order_direction])
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @mods }
    end
  end

  def show
    @mod = Mod.find(params[:id])

    respond_to do |format|
      format.html
      format.xml  { render :xml => @mod }
    end
  end

  def new
    @mod = Mod.new

    respond_to do |format|
      format.html
      format.xml  { render :xml => @mod }
    end
  end

  def edit
    @mod = Mod.find(params[:id])
  end

  def create
    @mod = Mod.new(params[:mod])

    respond_to do |format|
      if @mod.save
        format.html { redirect_to(@mod, :notice => 'Mod was successfully created.') }
        format.xml  { render :xml => @mod, :status => :created, :location => @mod }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mod.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @mod = Mod.find(params[:id])
    
    respond_to do |format|
      if @mod.send(:update_without_password, params[:mod])
        format.html { redirect_to(@mod, :notice => 'Mod was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mod.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @mod = Mod.find(params[:id])
    @mod.destroy

    respond_to do |format|
      format.html { redirect_to(mods_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_order(column, title=nil)
    title   ||= column.to_s.titleize
    is_order  = params[:order_by] == column.to_s
    ascending = params[:order_direction] == 'asc'
    direction = is_order && ascending ? 'desc' : 'asc'
    link_text = is_order ? (ascending ? "#{title} ^" : "#{title} v") : title

    link_to link_text, {:order_by => column, :order_direction => direction, :filters => params[:filters]}
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Weidulog
    = stylesheet_link_tag :all
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js', 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/jquery-ui.min.js'
    = csrf_meta_tag
  %body
    #topbar
    #wrapper
      #header
        = link_to image_tag('header.png'), root_path
      #menuwrap
        = link_to content_tag(:span, 'Upload', :class => 'invisible'), new_log_path, :id => 'm_upload'
        = link_to content_tag(:span, 'Search', :class => 'invisible'), logs_path, :id => 'm_search'
      #maintop
      #main
        %p.notice= notice
        %p.alert= alert
        = yield
      #mainbottom
      #maintop
      #footer
        = link_to content_tag(:span, 'Spellhold Studios', :class => 'invisible'), 'http://www.spellholdstudios.net', :id => 'shslogo'
        #footercontent
          %h2 Statistics
          %p Logs uploaded: #{Log.count}
          %p Mods catalogued: #{Mod.count}
      #mainbottom

app/views/logs/index.html.haml
= form_for :filters, :html => {:method => :get} do |f|
  %span #{f.label :author_contains, 'Author'}: #{f.text_field :author_contains, :value => params[:filters].try(:fetch, :author_contains)}
  %span #{f.label :created_at_eq, 'Date'}: #{f.text_field :created_at_eq, :value => params[:filters].try(:fetch, :created_at_eq)}
  %span #{f.label :mods_name_contains, 'Mod'}: #{f.text_field :mods_name_contains, :value => params[:filters].try(:fetch, :mods_name_contains)}
  %span #{f.submit 'Filter'}
%table{:style => 'width: 100%'}
  %tr
    %th= link_to_order(:author)
    %th= link_to_order(:created_at, 'Date')
    %th= link_to_order(:mod_count, '# of mods')
    %th= link_to_order(:mod_component_count, '# of components')
    %th Actions
  - @logs.each do |log|
    %tr
      %td= log.author
      %td= log.created_at.to_s(:long)
      %td= log.mod_count
      %td= log.mod_component_count
      %td= link_to 'View', log_path(log)
:javascript
  $("#filters_created_at_eq").datepicker({ dateFormat: 'yy-mm-dd' });

app/views/logs/new.html.haml
%h1 Upload log
= form_for @log, :html => {:multipart => true} do |f|
  - if @log.errors.any?
    #errors
      %h2 #{pluralize(@log.errors.count, "error")} prohibited this log from being saved:
      %ul
        - @log.errors.full_messages.each do |msg|
          %li= msg
  #up_right
    = recaptcha_tags :display => {:theme => 'white', :tabindex => 2}
  #up_left
    %h2 Select log...
    = f.fields_for :content do |ff|
      %p #{ff.file_field :file}
    %p #{f.label :game_id, 'Game'}: #{f.select :game_id, Game.all.map{|g| [g.name, g.id]}, :include_blank => true}
    %p #{f.label :author}: #{f.text_field :author}
  #up_bottom
    = f.submit '', :id => 'up_submit'

app/views/logs/show.html.haml
%p
  %strong Author:
  = @log.author
%p
  %strong Date:
  = @log.created_at.to_s(:long)
%p
  %strong Content:
%textarea{:style => 'width: 100%; height: 340px; white-space: nowrap;', :readonly => 'readonly'}= @log.content.body

app/views/mods/index.html.haml
%table{:style => 'width: 100%'}
  %tr
    %th= link_to_order(:name)
    %th Actions
  - @mods.each do |mod|
    %tr
      %td= mod.name
      %td= link_to 'View', mod_path(mod)